#!/usr/bin/env python3
"""Build the consolidated USERGUIDE Markdown and PDF outputs."""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DEFAULT_MD = ROOT / "docs" / "USERGUIDE.md"
DEFAULT_PDF = ROOT / "USERGUIDE.pdf"
PDF_PREAMBLE = ROOT / "docs" / "assets" / "pandoc_pdf_preamble.tex"
PLUGIN_GUIDE_GENERATOR = ROOT / "scripts_generate_plugin_guide.py"
DEFAULT_AUTHOR = "Colby Leider"
TEX_GYRE_FONT_DIR = (
    "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/"
)
TEX_GYRE_MATH_FONT_DIR = (
    "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre-math/"
)

USERGUIDE_SOURCES: tuple[Path, ...] = (
    ROOT / "README.md",
    ROOT / "docs" / "PLUGIN_GUIDE.md",
    ROOT / "docs" / "PUBLIC_ALPHA_NOTES.md",
    ROOT / "docs" / "CLI_REFERENCE.md",
    ROOT / "docs" / "EXTREME_COOKBOOK.md",
    ROOT / "docs" / "IR_SYNTHESIS.md",
    ROOT / "docs" / "AI_AUGMENTATION.md",
    ROOT / "docs" / "SCHEMA_REFERENCE.md",
    ROOT / "docs" / "IR_MORPH_QA.md",
    ROOT / "docs" / "SOFA_FEASIBILITY.md",
    ROOT / "docs" / "FIGURES.md",
    ROOT / "docs" / "HOMEBREW.md",
    ROOT / "docs" / "benchmarks" / "README.md",
    ROOT / "docs" / "REFERENCES.md",
)


def _rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def _build_markdown(author: str) -> str:
    generated_on = datetime.now().astimezone().strftime("%B %d, %Y")
    lines: list[str] = [
        "# verbx User Guide",
        "",
        f"_{author}, {generated_on}_",
        "",
        "_Generated by `python3 scripts_generate_docs_pdf.py`._",
        "",
        "This manual consolidates the README plus the user-facing guides,",
        "reference material, and practical tips shipped in `docs/`.",
        "",
        "## Included Sources",
        "",
    ]
    lines.extend(f"- `{_rel(path)}`" for path in USERGUIDE_SOURCES)
    lines.extend(["", "---", ""])

    for index, source in enumerate(USERGUIDE_SOURCES):
        if index > 0:
            lines.extend(["", "\\newpage", "", f"<!-- {_rel(source)} -->", ""])
        lines.append(_markdown_for_userguide(source).rstrip())
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _markdown_for_userguide(source: Path) -> str:
    """Return source Markdown adjusted for its new home in docs/USERGUIDE.md."""

    markdown = source.read_text(encoding="utf-8")
    if source == ROOT / "README.md":
        markdown = markdown.replace('src="docs/assets/', 'src="assets/')
        markdown = markdown.replace("](docs/assets/", "](assets/")
    return markdown


def _write_markdown(path: Path, author: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_build_markdown(author), encoding="utf-8")


def _pandoc_base_command(markdown_path: Path, author: str) -> list[str]:
    generated_on = datetime.now().astimezone().strftime("%B %d, %Y")
    return [
        "pandoc",
        str(markdown_path),
        "--from=gfm+tex_math_dollars+raw_attribute",
        "--toc",
        "--number-sections",
        "--standalone",
        "--resource-path=.:docs:examples",
        "--metadata=title:verbx User Guide",
        f"--metadata=author:{author}",
        f"--metadata=date:{generated_on}",
        "--include-in-header",
        str(PDF_PREAMBLE),
        "-V",
        "geometry:margin=1in",
        "-V",
        "colorlinks=true",
        "-V",
        "urlcolor=blue",
        "-V",
        "mainfont=texgyreschola-regular.otf",
        "-V",
        f"mainfontoptions:Path={TEX_GYRE_FONT_DIR}",
        "-V",
        "mainfontoptions:BoldFont=texgyreschola-bold.otf",
        "-V",
        "mainfontoptions:ItalicFont=texgyreschola-italic.otf",
        "-V",
        "mainfontoptions:BoldItalicFont=texgyreschola-bolditalic.otf",
        "-V",
        "mathfont=texgyreschola-math.otf",
        "-V",
        f"mathfontoptions:Path={TEX_GYRE_MATH_FONT_DIR}",
        "-V",
        "monofont=Menlo",
    ]


def _rewrite_longtable_specs(latex_path: Path) -> None:
    text = latex_path.read_text(encoding="utf-8")
    replacements = {
        r"\begin{longtable}[]{@{}ll@{}}": (
            r"\begin{longtable}[]{@{}>{\RaggedRight\arraybackslash\hspace{0pt}}p{0.26\linewidth}"
            r">{\RaggedRight\arraybackslash\hspace{0pt}}p{0.62\linewidth}@{}}"
        ),
        r"\begin{longtable}[]{@{}lll@{}}": (
            r"\begin{longtable}[]{@{}>{\RaggedRight\arraybackslash\hspace{0pt}}p{0.22\linewidth}"
            r">{\RaggedRight\arraybackslash\hspace{0pt}}p{0.34\linewidth}"
            r">{\RaggedRight\arraybackslash\hspace{0pt}}p{0.30\linewidth}@{}}"
        ),
        r"\begin{longtable}[]{@{}llll@{}}": (
            r"\begin{longtable}[]{@{}>{\RaggedRight\arraybackslash\hspace{0pt}}p{0.15\linewidth}"
            r">{\RaggedRight\arraybackslash\hspace{0pt}}p{0.23\linewidth}"
            r">{\RaggedRight\arraybackslash\hspace{0pt}}p{0.22\linewidth}"
            r">{\RaggedRight\arraybackslash\hspace{0pt}}p{0.30\linewidth}@{}}"
        ),
    }
    for old, new in replacements.items():
        text = text.replace(old, new)

    text = _rewrite_longtable_value_breaks(text)
    text = _rewrite_highlighting_token_breaks(text)
    text = _rewrite_texttt_breaks(text)
    text = _rewrite_figure_paths(text)
    latex_path.write_text(text, encoding="utf-8")


def _rewrite_figure_paths(text: str) -> str:
    """Resolve guide assets from the temporary LaTeX build directory."""

    figure_root = (ROOT / "docs" / "assets" / "userguide_figures").as_posix()
    asset_root = (ROOT / "docs" / "assets").as_posix()
    text = text.replace(
        r"{assets/userguide_figures/",
        rf"{{{figure_root}/",
    )
    return text.replace(r"{assets/", rf"{{{asset_root}/")


def _rewrite_longtable_value_breaks(text: str) -> str:
    """Add breakpoints to compact slash/comma lists inside tables only."""

    longtable_pattern = re.compile(r"(\\begin\{longtable\}.*?\\end\{longtable\})", re.DOTALL)

    def rewrite_block(match: re.Match[str]) -> str:
        block = match.group(1)
        protected_urls: list[str] = []

        def protect_url(url_match: re.Match[str]) -> str:
            protected_urls.append(url_match.group(0))
            return f"@@VERBX_HREF_URL_{len(protected_urls) - 1}@@"

        block = re.sub(r"\\href\{[^{}]*\}", protect_url, block)
        block = re.sub(r"(?<=[A-Za-z0-9_.\\])/(?=[A-Za-z0-9_.\\])", r"/\\allowbreak{}", block)
        block = re.sub(r"(?<=[A-Za-z0-9_.\\]),(?=[A-Za-z0-9_.\\])", r",\\allowbreak{}", block)
        block = re.sub(r"(?<=[A-Za-z0-9_.\\])=(?=[A-Za-z0-9_.\\])", r"=\\allowbreak{}", block)

        for index, url in enumerate(protected_urls):
            block = block.replace(f"@@VERBX_HREF_URL_{index}@@", url)
        return block

    return longtable_pattern.sub(rewrite_block, text)


def _rewrite_texttt_breaks(text: str) -> str:
    return _rewrite_macro_content_breaks(text, r"\texttt{")


def _rewrite_highlighting_token_breaks(text: str) -> str:
    for marker in (r"\StringTok{", r"\NormalTok{", r"\AttributeTok{"):
        text = _rewrite_macro_content_breaks(text, marker)
    return text


def _rewrite_macro_content_breaks(text: str, marker: str) -> str:
    parts: list[str] = []
    start = 0
    while True:
        idx = text.find(marker, start)
        if idx == -1:
            parts.append(text[start:])
            break
        parts.append(text[start : idx + len(marker)])
        cursor = idx + len(marker)
        depth = 1
        content_start = cursor
        while cursor < len(text) and depth > 0:
            char = text[cursor]
            if char == "{":
                depth += 1
            elif char == "}":
                depth -= 1
            cursor += 1
        content = text[content_start : cursor - 1]
        content = _insert_inline_breakpoints(content)
        parts.append(content)
        parts.append("}")
        start = cursor
    return "".join(parts)


def _insert_inline_breakpoints(content: str) -> str:
    content = content.replace(r"\_", r"\_\allowbreak{}")
    content = content.replace(r"\/", r"\/\allowbreak{}")
    content = re.sub(r"(?<!\\)/", r"/\\allowbreak{}", content)
    content = re.sub(r"(?<!\\)\.", r".\\allowbreak{}", content)
    content = content.replace(":", r":\allowbreak{}")
    content = content.replace("-", r"-\allowbreak{}")
    content = content.replace(",", r",\allowbreak{}")
    content = content.replace("=", r"=\allowbreak{}")
    return content


def _markdown_with_pdf_targets(markdown: str) -> str:
    """Make GitHub-style HTML anchors available to Pandoc's LaTeX backend."""

    def replace_anchor_run(match: re.Match[str]) -> str:
        anchor_run = match.group(0)
        anchor_ids = re.findall(r'id="([^"]+)"', anchor_run)
        label_lines = "\n".join(rf"\phantomsection\label{{{anchor_id}}}" for anchor_id in anchor_ids)
        return (
            anchor_run
            + "\n\n```{=latex}\n"
            + label_lines
            + "\n```"
        )

    markdown = re.sub(r'(?:<a\s+id="[^"]+"></a>)+', replace_anchor_run, markdown)
    return re.sub(
        r"^\\newpage$",
        lambda _: "```{=latex}\n\\newpage\n```",
        markdown,
        flags=re.MULTILINE,
    )


def _render_pdf(markdown_path: Path, pdf_path: Path, author: str) -> None:
    pdf_path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="verbx_userguide_") as tmpdir_raw:
        tmpdir = Path(tmpdir_raw)
        pdf_markdown_path = tmpdir / "userguide_pdf.md"
        latex_path = tmpdir / "userguide.tex"
        pdf_markdown_path.write_text(
            _markdown_with_pdf_targets(markdown_path.read_text(encoding="utf-8")),
            encoding="utf-8",
        )
        pandoc_command = [
            *_pandoc_base_command(pdf_markdown_path, author),
            "--to=latex",
            "-o",
            str(latex_path),
        ]
        subprocess.run(pandoc_command, cwd=ROOT, check=True)
        _rewrite_longtable_specs(latex_path)
        for _ in range(5):
            subprocess.run(
                [
                    "xelatex",
                    "-interaction=nonstopmode",
                    "-halt-on-error",
                    "-output-directory",
                    str(tmpdir),
                    str(latex_path),
                ],
                cwd=ROOT,
                check=True,
            )
        shutil.copy2(tmpdir / "userguide.pdf", pdf_path)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--markdown-out", type=Path, default=DEFAULT_MD)
    parser.add_argument("--pdf-out", type=Path, default=DEFAULT_PDF)
    parser.add_argument("--author", default=DEFAULT_AUTHOR)
    parser.add_argument(
        "--md-only",
        action="store_true",
        help="Only write the consolidated Markdown file and skip PDF rendering.",
    )
    args = parser.parse_args()

    subprocess.run([sys.executable, str(PLUGIN_GUIDE_GENERATOR)], cwd=ROOT, check=True)

    missing = [path for path in USERGUIDE_SOURCES if not path.exists()]
    if missing:
        for path in missing:
            print(f"Missing USERGUIDE source: {_rel(path)}", file=sys.stderr)
        return 2

    markdown_out = args.markdown_out.resolve()
    pdf_out = args.pdf_out.resolve()

    _write_markdown(markdown_out, str(args.author))
    print(f"Wrote {markdown_out}")

    if args.md_only:
        return 0

    try:
        _render_pdf(markdown_out, pdf_out, str(args.author))
    except subprocess.CalledProcessError as exc:
        print(f"Failed to render PDF with pandoc/xelatex: {exc}", file=sys.stderr)
        return exc.returncode or 1

    print(f"Wrote {pdf_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
