#!/usr/bin/env python3
"""Build the consolidated USERGUIDE Markdown and PDF outputs."""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DEFAULT_MD = ROOT / "docs" / "USERGUIDE.md"
DEFAULT_PDF = ROOT / "USERGUIDE.pdf"
PDF_PREAMBLE = ROOT / "docs" / "assets" / "pandoc_pdf_preamble.tex"
CARD_ILLUSTRATIONS = ROOT / "docs" / "assets" / "verbx_card_illustrations.tex"
INDEX_STYLE = ROOT / "docs" / "assets" / "verbx_index.ist"
REFERENCE_METADATA = ROOT / "docs" / "reference_metadata.json"
PLUGIN_GUIDE_GENERATOR = ROOT / "scripts_generate_plugin_guide.py"
BOOK_SUPPLEMENT_GENERATOR = ROOT / "scripts_generate_book_supplements.py"
DEFAULT_AUTHOR = "Colby Leider"
TEX_GYRE_FONT_DIR = (
    "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/"
)
TEX_GYRE_MATH_FONT_DIR = (
    "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre-math/"
)

USERGUIDE_SOURCES: tuple[Path, ...] = (
    ROOT / "README.md",
    ROOT / "docs" / "INTRODUCTORY_BLOCK_DIAGRAMS.md",
    ROOT / "docs" / "PUBLIC_ALPHA_NOTES.md",
    ROOT / "docs" / "CLI_REFERENCE.md",
    ROOT / "docs" / "EXTREME_COOKBOOK.md",
    ROOT / "docs" / "PLUGIN_GUIDE.md",
    ROOT / "docs" / "IR_SYNTHESIS.md",
    ROOT / "docs" / "AI_AUGMENTATION.md",
    ROOT / "docs" / "SCHEMA_REFERENCE.md",
    ROOT / "docs" / "IR_MORPH_QA.md",
    ROOT / "docs" / "SOFA_FEASIBILITY.md",
    ROOT / "docs" / "FIGURES.md",
    ROOT / "docs" / "HOMEBREW.md",
    ROOT / "docs" / "benchmarks" / "README.md",
    ROOT / "docs" / "MUSICAL_PIECES_APPENDIX.md",
    ROOT / "docs" / "MUSICAL_PIECES_EXPANSION.md",
    ROOT / "docs" / "HOMEWORK_ASSIGNMENTS.md",
    ROOT / "docs" / "REFERENCES.md",
)


def _rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def _build_markdown(author: str) -> str:
    generated_on = datetime.now().astimezone().strftime("%B %d, %Y")
    lines: list[str] = [
        "# verbx User Guide",
        "",
        f"_{author}, {generated_on}_",
        "",
        "_Generated by `python3 scripts_generate_docs_pdf.py`._",
        "",
        "This manual consolidates the README plus the user-facing guides,",
        "reference material, and practical tips shipped in `docs/`.",
        "",
        "## Included Sources",
        "",
    ]
    lines.extend(f"- `{_rel(path)}`" for path in USERGUIDE_SOURCES)
    lines.extend(["", "---", ""])

    for index, source in enumerate(USERGUIDE_SOURCES):
        if index > 0:
            lines.extend(["", "\\newpage", "", f"<!-- {_rel(source)} -->", ""])
        lines.append(_markdown_for_userguide(source).rstrip())
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _markdown_for_userguide(source: Path) -> str:
    """Return source Markdown adjusted for its new home in docs/USERGUIDE.md."""

    markdown = source.read_text(encoding="utf-8")
    if source == ROOT / "docs" / "CLI_REFERENCE.md":
        # Rich/Typer pads captured help to terminal width; that spacing has no
        # semantic value inside fenced blocks and makes the generated book dirty.
        markdown = "\n".join(line.rstrip() for line in markdown.splitlines()) + "\n"
    if source == ROOT / "README.md":
        markdown = markdown.replace('src="docs/assets/', 'src="assets/')
        markdown = markdown.replace("](docs/assets/", "](assets/")
    return markdown


def _write_markdown(path: Path, author: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_build_markdown(author), encoding="utf-8")


def _pandoc_base_command(markdown_path: Path, author: str) -> list[str]:
    generated_on = datetime.now().astimezone().strftime("%B %d, %Y")
    return [
        "pandoc",
        str(markdown_path),
        "--from=gfm+tex_math_dollars+raw_attribute",
        "--toc",
        "--list-of-figures",
        "--number-sections",
        "--standalone",
        "--top-level-division=chapter",
        "--resource-path=.:docs:examples",
        "--metadata=title:verbx User Guide",
        "--metadata=subtitle:Reverb, Spatial Audio, Dereverberation, Plug-in Design, and Educational Exercises",
        f"--metadata=author:{author}",
        f"--metadata=date:{generated_on}",
        "--include-in-header",
        str(PDF_PREAMBLE),
        "--include-in-header",
        str(CARD_ILLUSTRATIONS),
        "-V",
        "documentclass=book",
        "-V",
        "classoption=openany",
        "-V",
        "papersize=letter",
        "-V",
        "toc-depth=2",
        "-V",
        "geometry:margin=1in",
        "-V",
        "colorlinks=true",
        "-V",
        "urlcolor=blue",
        "-V",
        "mainfont=texgyreschola-regular.otf",
        "-V",
        f"mainfontoptions:Path={TEX_GYRE_FONT_DIR}",
        "-V",
        "mainfontoptions:BoldFont=texgyreschola-bold.otf",
        "-V",
        "mainfontoptions:ItalicFont=texgyreschola-italic.otf",
        "-V",
        "mainfontoptions:BoldItalicFont=texgyreschola-bolditalic.otf",
        "-V",
        "mathfont=texgyreschola-math.otf",
        "-V",
        f"mathfontoptions:Path={TEX_GYRE_MATH_FONT_DIR}",
        "-V",
        "monofont=Menlo",
    ]


def _rewrite_longtable_specs(latex_path: Path) -> None:
    text = latex_path.read_text(encoding="utf-8")
    replacements = {
        r"\begin{longtable}[]{@{}ll@{}}": (
            r"\begin{longtable}[]{@{}>{\RaggedRight\arraybackslash\hspace{0pt}}p{0.26\linewidth}"
            r">{\RaggedRight\arraybackslash\hspace{0pt}}p{0.62\linewidth}@{}}"
        ),
        r"\begin{longtable}[]{@{}lll@{}}": (
            r"\begin{longtable}[]{@{}>{\RaggedRight\arraybackslash\hspace{0pt}}p{0.22\linewidth}"
            r">{\RaggedRight\arraybackslash\hspace{0pt}}p{0.34\linewidth}"
            r">{\RaggedRight\arraybackslash\hspace{0pt}}p{0.30\linewidth}@{}}"
        ),
        r"\begin{longtable}[]{@{}llll@{}}": (
            r"\begin{longtable}[]{@{}>{\RaggedRight\arraybackslash\hspace{0pt}}p{0.15\linewidth}"
            r">{\RaggedRight\arraybackslash\hspace{0pt}}p{0.23\linewidth}"
            r">{\RaggedRight\arraybackslash\hspace{0pt}}p{0.22\linewidth}"
            r">{\RaggedRight\arraybackslash\hspace{0pt}}p{0.30\linewidth}@{}}"
        ),
    }
    for old, new in replacements.items():
        text = text.replace(old, new)

    text = _rewrite_longtable_value_breaks(text)
    text = _rewrite_highlighting_token_breaks(text)
    text = _rewrite_texttt_breaks(text)
    text = _rewrite_figure_paths(text)
    latex_path.write_text(text, encoding="utf-8")


def _rewrite_figure_paths(text: str) -> str:
    """Resolve guide assets from the temporary LaTeX build directory."""

    figure_root = (ROOT / "docs" / "assets" / "userguide_figures").as_posix()
    asset_root = (ROOT / "docs" / "assets").as_posix()
    text = text.replace(
        r"{assets/userguide_figures/",
        rf"{{{figure_root}/",
    )
    return text.replace(r"{assets/", rf"{{{asset_root}/")


def _rewrite_longtable_value_breaks(text: str) -> str:
    """Add breakpoints to compact slash/comma lists inside tables only."""

    longtable_pattern = re.compile(r"(\\begin\{longtable\}.*?\\end\{longtable\})", re.DOTALL)

    def rewrite_block(match: re.Match[str]) -> str:
        block = match.group(1)
        protected_urls: list[str] = []

        def protect_url(url_match: re.Match[str]) -> str:
            protected_urls.append(url_match.group(0))
            return f"@@VERBX_HREF_URL_{len(protected_urls) - 1}@@"

        block = re.sub(r"\\href\{[^{}]*\}", protect_url, block)
        block = re.sub(r"(?<=[A-Za-z0-9_.\\])/(?=[A-Za-z0-9_.\\])", r"/\\allowbreak{}", block)
        block = re.sub(r"(?<=[A-Za-z0-9_.\\]),(?=[A-Za-z0-9_.\\])", r",\\allowbreak{}", block)
        block = re.sub(r"(?<=[A-Za-z0-9_.\\])=(?=[A-Za-z0-9_.\\])", r"=\\allowbreak{}", block)

        for index, url in enumerate(protected_urls):
            block = block.replace(f"@@VERBX_HREF_URL_{index}@@", url)
        return block

    return longtable_pattern.sub(rewrite_block, text)


def _rewrite_texttt_breaks(text: str) -> str:
    return _rewrite_macro_content_breaks(text, r"\texttt{")


def _rewrite_highlighting_token_breaks(text: str) -> str:
    for marker in (r"\StringTok{", r"\NormalTok{", r"\AttributeTok{"):
        text = _rewrite_macro_content_breaks(text, marker)
    return text


def _rewrite_macro_content_breaks(text: str, marker: str) -> str:
    parts: list[str] = []
    start = 0
    while True:
        idx = text.find(marker, start)
        if idx == -1:
            parts.append(text[start:])
            break
        parts.append(text[start : idx + len(marker)])
        cursor = idx + len(marker)
        depth = 1
        content_start = cursor
        while cursor < len(text) and depth > 0:
            char = text[cursor]
            if char == "{":
                depth += 1
            elif char == "}":
                depth -= 1
            cursor += 1
        content = text[content_start : cursor - 1]
        content = _insert_inline_breakpoints(content)
        parts.append(content)
        parts.append("}")
        start = cursor
    return "".join(parts)


def _insert_inline_breakpoints(content: str) -> str:
    content = content.replace(r"\_", r"\_\allowbreak{}")
    content = content.replace(r"\/", r"\/\allowbreak{}")
    content = re.sub(r"(?<!\\)/", r"/\\allowbreak{}", content)
    content = re.sub(r"(?<!\\)\.", r".\\allowbreak{}", content)
    content = content.replace(":", r":\allowbreak{}")
    content = content.replace("-", r"-\allowbreak{}")
    content = content.replace(",", r",\allowbreak{}")
    content = content.replace("=", r"=\allowbreak{}")
    return content


def _markdown_with_pdf_targets(markdown: str) -> str:
    """Make GitHub-style HTML anchors available to Pandoc's LaTeX backend."""

    def replace_anchor_run(match: re.Match[str]) -> str:
        anchor_run = match.group(0)
        anchor_ids = re.findall(r'id="([^"]+)"', anchor_run)
        label_lines = "\n".join(rf"\phantomsection\label{{{anchor_id}}}" for anchor_id in anchor_ids)
        return (
            anchor_run
            + "\n\n```{=latex}\n"
            + label_lines
            + "\n```"
        )

    markdown = _remove_generated_pdf_preamble(markdown)
    markdown = _add_book_parts(markdown)
    markdown = _italicize_musical_titles(markdown)
    markdown = re.sub(r'(?:<a\s+id="[^"]+"></a>)+', replace_anchor_run, markdown)
    markdown = _ensure_image_captions(markdown)
    markdown = _compact_illustrated_guide(markdown)
    markdown = _illustrate_operational_cards(markdown)
    markdown = _convert_figure_captions(markdown)
    markdown = _strip_plugin_heading_numbers(markdown)
    markdown = markdown.replace(
        "# Important Musical Pieces",
        "```{=latex}\n\\appendix\n```\n\n# Important Musical Pieces",
        1,
    )
    markdown = markdown.replace(
        "# Research Papers and References",
        "```{=latex}\n\\cleardoublepage\n```\n\n# Research Papers and References",
        1,
    )
    markdown = _add_pdf_index(markdown)
    return re.sub(
        r"^\\newpage$",
        lambda _: "```{=latex}\n\\newpage\n```",
        markdown,
        flags=re.MULTILINE,
    )


def _remove_generated_pdf_preamble(markdown: str) -> str:
    """Drop the consolidated-source manifest; the book has real front matter."""

    readme_start = markdown.find("\n# verbx\n")
    return markdown[readme_start + 1 :] if readme_start != -1 else markdown


def _add_book_parts(markdown: str) -> str:
    """Insert the three editorial divisions used by the PDF book."""

    divisions = (
        ("# verbx\n", "User Manual and Workflows"),
        ("# VERBX AUv3/VST3 Plug-in Handbook\n", "Plug-in Architecture and Operational Cards"),
        ("# IR Synthesis — A Dual-Layer Reference\n", "DSP, Impulse Responses, and Technical Reference"),
    )
    for heading, part_title in divisions:
        marker = f"```{{=latex}}\n\\part{{{part_title}}}\n```\n\n"
        markdown = markdown.replace(heading, marker + heading, 1)
    return markdown


def _italicize_musical_titles(markdown: str) -> str:
    """Enforce book-style italics for work titles in Appendix A."""

    start = markdown.find("# Important Musical Pieces")
    end = markdown.find("# Educational Exercises and Project Assignments", start)
    if start == -1:
        return markdown
    if end == -1:
        end = len(markdown)
    appendix = markdown[start:end]
    lead_pattern = re.compile(
        r"(?m)^\*\*(?P<creator>[^,*\n]+(?:,\s+[^,*\n]+)*),\s+"
        r"(?P<title>(?!\*)[^\n]+?)\s+\((?P<date>[^)]+)\)\.\*\*"
    )

    def italicize(match: re.Match[str]) -> str:
        return f"**{match.group('creator')}, *{match.group('title')}* ({match.group('date')}).**"

    appendix = lead_pattern.sub(italicize, appendix)
    return markdown[:start] + appendix + markdown[end:]


def _ensure_image_captions(markdown: str) -> str:
    """Add a descriptive caption marker after every otherwise unlabeled image."""

    lines = markdown.splitlines()
    output: list[str] = []
    image_pattern = re.compile(r"^!\[(?P<alt>[^]]*)\]\([^)]+\)\s*$")
    caption_pattern = re.compile(r"^\*\*(?:Figure|Block diagram)")
    for index, line in enumerate(lines):
        output.append(line)
        match = image_pattern.match(line)
        if not match:
            continue
        cursor = index + 1
        while cursor < len(lines) and not lines[cursor].strip():
            cursor += 1
        if cursor < len(lines) and caption_pattern.match(lines[cursor]):
            continue
        title = re.sub(
            r"^(?:Figure|Block diagram)\s+\d+\s*:\s*",
            "",
            match.group("alt"),
            flags=re.IGNORECASE,
        ).strip().rstrip(".") or "Illustration"
        output.extend(("", f"**Figure: {title}.**"))
    return "\n".join(output)


def _convert_figure_captions(markdown: str) -> str:
    """Replace prose caption markers with the book's global figure counter."""

    pattern = re.compile(
        r"(?m)^\*\*(?:Figure(?:\s+\d+)?|Block diagram\s+\d+)[.:]\s*"
        r"(?P<title>.+?)\.?\*\*(?P<rest>[^\n]*)$"
    )

    def convert(match: re.Match[str]) -> str:
        title = _latex_text(match.group("title").rstrip("."))
        rest = match.group("rest").strip()
        caption = f"```{{=latex}}\n\\verbxFigureCaption{{{title}}}\n```"
        return caption + (f"\n\n{rest}" if rest else "")

    return pattern.sub(convert, markdown)


def _illustrate_operational_cards(markdown: str) -> str:
    """Give every generated operational card a dedicated vector illustration."""

    start = markdown.find("## 19. Production Starting-Point Cards")
    end = markdown.find("## 32. Closing Checklist", start)
    if start == -1 or end == -1:
        return markdown

    handbook = markdown[start:end]
    handbook = re.sub(r"(?m)^###\s+(?:19|2[0-9]|3[01])\.\d+\s+.*?\n+", "", handbook)

    section_pattern = re.compile(r"(?m)^##\s+(?:19|2[0-9]|3[01])\.\s+(.+?)\s*$")

    def section_visual(match: re.Match[str]) -> str:
        title = _latex_text(match.group(1))
        return (
            match.group(0)
            + "\n\n```{=latex}\n"
            + f"\\verbxCardSection{{{title}}}\n"
            + "```"
        )

    handbook = section_pattern.sub(section_visual, handbook)

    card_pattern = re.compile(
        r"(?ms)^(?P<title>\*\*(?:Production|Automation|Quality|Validation|Troubleshooting|Preset|Interaction|Audition|Asset|Release|Bus|Signal-test|Triage) card.*?\*\*)\n"
        r"(?P<body>.*?)(?=^\\newpage\s*$)"
    )

    def illustrate_card(match: re.Match[str]) -> str:
        title_line = match.group("title")
        title = title_line.removeprefix("**").removesuffix("**")
        command = _card_visual_command(title)
        return (
            "```{=latex}\n\\clearpage\n```\n\n"
            + title_line
            + "\n"
            + match.group("body").rstrip()
            + "\n\n```{=latex}\n"
            + "\\vfill\n"
            + f"\\verbxFigureCaption{{{_latex_text(title)} illustration}}\n"
            + command
            + "\n```\n\n"
        )

    handbook, card_count = card_pattern.subn(illustrate_card, handbook)
    if card_count != 588:
        raise ValueError(f"Expected 588 operational cards, found {card_count}")

    handbook = re.sub(
        r"(?m)^(#{2,3})\s+(?:\d+(?:\.\d+)*)\.?(?:\s+)(.+?)$",
        r"\1 \2",
        handbook,
    )
    return markdown[:start] + handbook + markdown[end:]


def _strip_plugin_heading_numbers(markdown: str) -> str:
    """Let the book class number structural headings without duplicated labels."""

    return re.sub(
        r"(?m)^(#{2,3})\s+(?:\d+(?:\.\d+)*)\.?(?:\s+)(.+?)$",
        r"\1 \2",
        markdown,
    )


def _card_visual_command(title: str) -> str:
    """Map a generated card title to one of the book's diagram grammars."""

    patterns: tuple[tuple[str, str], ...] = (
        (r"Production card: (.+) in (.+)", "verbxProductionVisual"),
        (r"Automation card: (.+) - (.+)", "verbxAutomationVisual"),
        (r"Validation card: (.+) - (.+)", "verbxValidationVisual"),
        (r"Preset card: (.+) / (.+)", "verbxPresetVisual"),
        (r"Interaction card \d+: (.+) with (.+)", "verbxInteractionVisual"),
        (r"Audition card: (.+) on (.+)", "verbxMonitoringVisual"),
        (r"Asset card: (.+) - (.+)", "verbxAssetVisual"),
        (r"Release card: (.+) - (.+)", "verbxReleaseVisual"),
        (r"Bus card: (.+) - (.+)", "verbxBusVisual"),
        (r"Signal-test card: (.+) with (.+)", "verbxSignalVisual"),
        (r"Triage card: (.+) - (.+)", "verbxTriageVisual"),
    )
    for pattern, macro in patterns:
        match = re.fullmatch(pattern, title)
        if match:
            left, right = (_latex_text(value) for value in match.groups())
            return rf"\{macro}{{{left}}}{{{right}}}"

    quality = re.fullmatch(r"Quality card \d+: (\d+) Hz, (.+), (\d+) frames", title)
    if quality:
        rate, mode, block = (_latex_text(value) for value in quality.groups())
        return rf"\verbxQualityVisual{{{rate} Hz}}{{{mode}}}{{{block} frames}}"

    troubleshooting = re.fullmatch(r"Troubleshooting card \d+: (.+)", title)
    if troubleshooting:
        return rf"\verbxTroubleshootingVisual{{{_latex_text(troubleshooting.group(1))}}}"
    raise ValueError(f"No illustration mapping for card title: {title}")


def _latex_text(value: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$",
        "#": r"\#", "_": r"\_", "{": r"\{", "}": r"\}",
        "~": r"\textasciitilde{}", "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(char, char) for char in value)


def _compact_illustrated_guide(markdown: str) -> str:
    """Typeset each illustrated-guide image beside its long description."""

    start = markdown.find("# Illustrated Guide")
    if start == -1:
        return markdown
    end = markdown.find("\n\\newpage\n", start)
    if end == -1:
        end = len(markdown)

    chapter = markdown[start:end]
    entry_pattern = re.compile(
        r"(?P<image>!\[Figure\s+\d+:[^\n]+\]\([^\n]+\))\n\n"
        r"\*\*Figure\s+\d+[.:]\s+(?P<title>.+?)\.\*\*\s*"
        r"(?P<summary>.*?)(?=\n\n)\n\n"
        r"(?P<description>Read the figure.*?)(?=\n\n(?:!\[Figure|##\s)|\Z)",
        re.DOTALL,
    )

    def compact_entry(match: re.Match[str]) -> str:
        return (
            "```{=latex}\n"
            "\\par\\medskip\\noindent\n"
            "\\begin{minipage}[t]{0.43\\textwidth}\\vspace{0pt}\n"
            "```\n\n"
            f"{match.group('image')}\n\n"
            "```{=latex}\n"
            "\\end{minipage}\\hfill\n"
            "\\begin{minipage}[t]{0.54\\textwidth}\\vspace{0pt}\n"
            "```\n\n"
            f"**Figure: {match.group('title')}.** {match.group('summary').strip()}\n\n"
            f"{match.group('description')}\n\n"
            "```{=latex}\n"
            "\\end{minipage}\\par\\medskip\n"
            "```"
        )

    compacted, count = entry_pattern.subn(compact_entry, chapter)
    if count != 100:
        raise ValueError(f"Expected 100 illustrated-guide entries, found {count}")
    return markdown[:start] + compacted + markdown[end:]


def _add_pdf_index(markdown: str) -> str:
    """Build a deep textbook index from structure, controls, cards, and citations."""

    markdown = _index_markdown_headings(markdown)
    markdown = _index_cli_terms(markdown)
    markdown = _index_operational_cards(markdown)
    markdown = _index_bibliography(markdown)
    markdown = _typeset_research_references(markdown)

    figure_pattern = re.compile(
        r"(?m)^(?P<command>\\verbxFigureCaption\{(?P<title>.+?)\})$"
    )

    def index_figure(match: re.Match[str]) -> str:
        term = _plain_index_term(match.group("title"))
        return match.group("command") + f"\n\\index{{{_latex_index_term(term)}}}"

    markdown = figure_pattern.sub(index_figure, markdown)

    appendix_start = markdown.find("# Important Musical Pieces")
    if appendix_start != -1:
        appendix = markdown[appendix_start:]
        work_pattern = re.compile(r"(?m)^\*\*(?P<term>.+?\([^)]+\))\.\*\*")

        def index_work(match: re.Match[str]) -> str:
            term = _plain_index_term(match.group("term"))
            marker = f"```{{=latex}}\n\\index{{{_latex_index_term(term)}}}\n```\n\n"
            return marker + match.group(0)

        appendix = work_pattern.sub(index_work, appendix)
        markdown = markdown[:appendix_start] + appendix
    return (
        markdown.rstrip()
        + "\n\n```{=latex}\n"
        + "\\backmatter\n"
        + "\\clearpage\n"
        + "\\phantomsection\n"
        + "\\addcontentsline{toc}{chapter}{Index}\n"
        + "\\printindex\n"
        + "\\verbxColophon\n"
        + "```\n"
    )


def _index_cli_terms(markdown: str) -> str:
    """Index each distinct CLI flag and command at its first useful occurrence."""

    flag_pattern = re.compile(r"(?<![\w-])--[a-z][a-z0-9-]+")
    command_pattern = re.compile(r"\bverbx\s+[a-z][a-z0-9-]*(?:\s+[a-z][a-z0-9-]*)?")
    fence_pattern = re.compile(r"^\s*(`{3,}|~{3,})")
    seen: set[str] = set()
    pending: list[str] = []
    output: list[str] = []
    active_fence: str | None = None

    def markers(terms: list[str]) -> list[str]:
        if not terms:
            return []
        commands = "\n".join(
            rf"\index{{{_latex_index_hierarchical('CLI', term)}}}" for term in terms
        )
        return ["", "```{=latex}", commands, "```", ""]

    for line in markdown.splitlines():
        fence = fence_pattern.match(line)
        terms = [*flag_pattern.findall(line), *command_pattern.findall(line)]
        fresh = [term for term in terms if term not in seen]
        seen.update(fresh)
        if active_fence is None and fresh:
            output.extend(markers(fresh))
        elif active_fence is not None:
            pending.extend(fresh)
        output.append(line)
        if fence:
            marker = fence.group(1)[0]
            if active_fence == marker:
                active_fence = None
                output.extend(markers(pending))
                pending.clear()
            elif active_fence is None:
                active_fence = marker
    return "\n".join(output)


def _index_operational_cards(markdown: str) -> str:
    """Make all 588 operational-card subjects discoverable."""

    pattern = re.compile(
        r"(?m)^(?P<title>\*\*(?:Production|Automation|Quality|Validation|Troubleshooting|Preset|Interaction|Audition|Asset|Release|Bus|Signal-test|Triage) card.*?\*\*)$"
    )

    def add_marker(match: re.Match[str]) -> str:
        term = _plain_index_term(match.group("title"))
        family = term.split(" card", 1)[0] + " cards"
        return (
            "```{=latex}\n"
            + rf"\index{{{_latex_index_hierarchical('Operational cards', term)}}}" + "\n"
            + rf"\index{{{_latex_index_hierarchical(family, term)}}}" + "\n"
            + "```\n\n"
            + match.group(0)
        )

    return pattern.sub(add_marker, markdown)


def _index_bibliography(markdown: str) -> str:
    """Index every parsed paper author and title, including normalized Jot entries."""

    start = markdown.find("# Research Papers and References")
    if start == -1:
        return markdown
    references = markdown[start:]
    entry_pattern = re.compile(
        r"(?m)^(?P<entry>\*\*\[[^]]+\]\*\*\s+"
        r"(?P<authors>.+?)\s+\((?P<year>(?:18|19|20)\d{2}[a-z]?|n\.d\.)\)\.\s+"
        r"(?P<title>.+?)\.\s+\*[^*]+\*\..*)$"
    )

    def index_entry(match: re.Match[str]) -> str:
        authors = re.split(r"\s*;\s*|\s+&\s+|\s+and\s+", match.group("authors"))
        normalized: list[str] = []
        for author in authors:
            author = re.sub(r"\s+", " ", author).strip(" ,")
            if author.lower() == "et al.":
                continue
            if author in {"Jot, J.-M.", "Jot, J. M."}:
                author = "Jot, Jean-Marc"
            if author and author not in normalized:
                normalized.append(author)
        terms: list[tuple[str, str]] = []
        for author in normalized:
            terms.extend((("Authors", author), ("", author)))
        title = _plain_index_term(match.group("title"))
        if title:
            terms.append(("Research papers", title))
        commands = "\n".join(
            rf"\index{{{_latex_index_hierarchical(category, term) if category else _latex_index_term(term)}}}"
            for category, term in terms
        )
        return f"```{{=latex}}\n{commands}\n```\n\n{match.group('entry')}"

    references = entry_pattern.sub(index_entry, references)
    return markdown[:start] + references


def _typeset_research_references(markdown: str) -> str:
    """Render DOI records as consistent hanging bibliography entries."""

    start = markdown.find("# Research Papers and References")
    if start == -1:
        return markdown
    metadata: dict[str, dict[str, str]] = {}
    if REFERENCE_METADATA.exists():
        metadata = json.loads(REFERENCE_METADATA.read_text(encoding="utf-8"))
    references = markdown[start:]
    pattern = re.compile(
        r"(?m)^\*\*\[(?P<key>[^]]+)\]\*\*\s+(?P<authors>.+?)\s+"
        r"\((?P<year>(?:18|19|20)\d{2}[a-z]?|n\.d\.)\)\.\s+"
        r"(?P<title>.+?)\.\s+\*(?P<venue>[^*]+)\*\.\s+"
        r"(?:DOI:\s+\[(?P<doi>[^]]+)\]\([^)]+\)|(?P<note>\(Also listed as \[[^]]+\]\)))"
    )

    def typeset(match: re.Match[str]) -> str:
        doi = match.group("doi") or ""
        record = metadata.get(doi.lower(), {})
        detail = _reference_detail(record)
        authors = _reference_authors(match.group("authors"))
        identifier = (
            ". DOI: \\href{https://doi.org/"
            + doi
            + "}{\\nolinkurl{"
            + doi
            + "}}"
            if doi
            else ". " + _latex_text(match.group("note") or "No DOI supplied")
        )
        return (
            "```{=latex}\n"
            "\\par\\noindent\\hangindent=1.7em\\hangafter=1\n"
            + _latex_text(authors.rstrip("."))
            + ". ``"
            + _latex_text(match.group("title").strip('"').rstrip("."))
            + ("'' " if match.group("title").rstrip().endswith(("?", "!")) else ".'' ")
            + "\\textit{"
            + _latex_text(match.group("venue"))
            + "}"
            + detail
            + identifier
            + ", "
            + _latex_text(match.group("year"))
            + ".\\hfill{\\scriptsize\\color{verbxCover} ["
            + _latex_text(match.group("key"))
            + "]}\\par\\smallskip\n"
            "```"
        )

    references, count = pattern.subn(typeset, references)
    if count != 1002:
        raise ValueError(f"Expected 1002 research references, formatted {count}")
    return markdown[:start] + references


def _reference_authors(value: str) -> str:
    formatted: list[str] = []
    for author in re.split(r"\s*;\s*", value):
        author = author.strip()
        if not author or author.lower() == "et al.":
            formatted.append("et al.")
            continue
        if author == "Unknown authors" or "," not in author:
            formatted.append(author)
            continue
        family, given = (part.strip() for part in author.split(",", 1))
        initials = " ".join(
            token if re.fullmatch(r"(?:[A-ZÀ-ÖØ-Þ]\.?(?:-[A-ZÀ-ÖØ-Þ]\.?)*)", token) else token[0].upper() + "."
            for token in re.findall(r"[A-Za-zÀ-ÖØ-öø-ÿ]+(?:-[A-Za-zÀ-ÖØ-öø-ÿ]+)?\.?", given)
            if token
        )
        formatted.append(f"{family}, {initials}" if initials else family)
    return "; ".join(formatted)


def _reference_detail(record: dict[str, str]) -> str:
    volume = record.get("volume", "")
    issue = record.get("issue", "")
    page = record.get("page", "").replace("-", "--")
    if not any((volume, issue, page)):
        return ""
    volume_issue = volume + (f"({issue})" if issue else "")
    if volume_issue and page:
        return f" { _latex_text(volume_issue) }: { _latex_text(page) }"
    return " " + _latex_text(volume_issue or page)


def _latex_index_hierarchical(category: str, term: str) -> str:
    return f"{_latex_index_term(category)}!{_latex_index_term(term)}"


def _index_markdown_headings(markdown: str) -> str:
    """Add index markers to headings without touching fenced code examples."""

    heading_pattern = re.compile(r"^(#{1,6})\s+(.+?)\s*$")
    fence_pattern = re.compile(r"^\s*(`{3,}|~{3,})")
    output: list[str] = []
    active_fence: str | None = None

    for line in markdown.splitlines():
        fence_match = fence_pattern.match(line)
        if fence_match:
            marker = fence_match.group(1)[0]
            active_fence = None if active_fence == marker else marker
            output.append(line)
            continue

        output.append(line)
        if active_fence is not None:
            continue

        heading_match = heading_pattern.match(line)
        if not heading_match:
            continue
        term = _plain_index_term(heading_match.group(2))
        if not term or term.lower() in {"contents", "index"}:
            continue
        output.extend(("", "```{=latex}", f"\\index{{{_latex_index_term(term)}}}", "```"))

    return "\n".join(output)


def _plain_index_term(value: str) -> str:
    """Reduce Markdown heading or caption text to a readable index term."""

    value = re.sub(r"\{#[^}]+\}\s*$", "", value)
    value = re.sub(r"!\[([^]]*)\]\([^)]*\)", r"\1", value)
    value = re.sub(r"\[([^]]+)\]\([^)]*\)", r"\1", value)
    value = re.sub(r"<[^>]+>", "", value)
    value = value.replace("`", "").replace("*", "").replace("_", " ")
    value = re.sub(r"\s+", " ", value).strip(" .")
    value = re.sub(r"^(?:\d+(?:\.\d+)*|\d+[A-Za-z])[.)]?\s+", "", value)
    if re.fullmatch(r"(?:5\.1|7\.1|7\.1\.4)", value):
        value = f"Surround format {value}"
    return value


def _latex_index_term(value: str) -> str:
    """Escape text for both makeindex syntax and the resulting LaTeX file."""

    value = value.replace('"', "").replace("!", " - ").replace("@", " at ").replace("|", " / ")
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(char, char) for char in value)


def _render_pdf(markdown_path: Path, pdf_path: Path, author: str) -> None:
    pdf_path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="verbx_userguide_") as tmpdir_raw:
        tmpdir = Path(tmpdir_raw)
        pdf_markdown_path = tmpdir / "userguide_pdf.md"
        latex_path = tmpdir / "userguide.tex"
        pdf_markdown_path.write_text(
            _markdown_with_pdf_targets(markdown_path.read_text(encoding="utf-8")),
            encoding="utf-8",
        )
        pandoc_command = [
            *_pandoc_base_command(pdf_markdown_path, author),
            "--to=latex",
            "-o",
            str(latex_path),
        ]
        subprocess.run(pandoc_command, cwd=ROOT, check=True)
        _rewrite_longtable_specs(latex_path)
        for pass_index in range(5):
            subprocess.run(
                [
                    "xelatex",
                    "-interaction=nonstopmode",
                    "-halt-on-error",
                    "-output-directory",
                    str(tmpdir),
                    str(latex_path),
                ],
                cwd=ROOT,
                check=True,
            )
            if pass_index == 0:
                subprocess.run(
                    ["makeindex", "-s", str(INDEX_STYLE), "userguide.idx"],
                    cwd=tmpdir,
                    check=True,
                )
        shutil.copy2(tmpdir / "userguide.pdf", pdf_path)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--markdown-out", type=Path, default=DEFAULT_MD)
    parser.add_argument("--pdf-out", type=Path, default=DEFAULT_PDF)
    parser.add_argument("--author", default=DEFAULT_AUTHOR)
    parser.add_argument(
        "--md-only",
        action="store_true",
        help="Only write the consolidated Markdown file and skip PDF rendering.",
    )
    args = parser.parse_args()

    subprocess.run([sys.executable, str(PLUGIN_GUIDE_GENERATOR)], cwd=ROOT, check=True)
    subprocess.run([sys.executable, str(BOOK_SUPPLEMENT_GENERATOR)], cwd=ROOT, check=True)

    missing = [path for path in USERGUIDE_SOURCES if not path.exists()]
    if missing:
        for path in missing:
            print(f"Missing USERGUIDE source: {_rel(path)}", file=sys.stderr)
        return 2

    markdown_out = args.markdown_out.resolve()
    pdf_out = args.pdf_out.resolve()

    _write_markdown(markdown_out, str(args.author))
    print(f"Wrote {markdown_out}")

    if args.md_only:
        return 0

    try:
        _render_pdf(markdown_out, pdf_out, str(args.author))
    except subprocess.CalledProcessError as exc:
        print(f"Failed to render PDF with pandoc/xelatex: {exc}", file=sys.stderr)
        return exc.returncode or 1

    print(f"Wrote {pdf_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
