#!/usr/bin/env python3
"""Generate and optionally verify the CLI help reference document.

This keeps the published command reference synchronized with actual Typer help output.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from typer.testing import CliRunner

from verbx.cli import app

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT = ROOT / "docs" / "CLI_REFERENCE.md"
ANSI_ESCAPE_RE = re.compile(r"\x1B\[[0-?]*[ -/]*[@-~]")

HELP_COMMANDS: tuple[tuple[str, ...], ...] = (
    (),
    ("render",),
    ("realtime",),
    ("room-model",),
    ("analyze",),
    ("suggest",),
    ("quickstart",),
    ("doctor",),
    ("presets",),
    ("version",),
    ("ir",),
    ("ir", "gen"),
    ("ir", "analyze"),
    ("ir", "process"),
    ("ir", "morph"),
    ("ir", "morph-sweep"),
    ("ir", "fit"),
    ("batch",),
    ("batch", "template"),
    ("batch", "augment-template"),
    ("batch", "augment-profiles"),
    ("batch", "augment"),
    ("batch", "render"),
    ("immersive",),
    ("immersive", "template"),
    ("immersive", "handoff"),
    ("immersive", "qc"),
    ("immersive", "queue"),
    ("immersive", "queue", "template"),
    ("immersive", "queue", "status"),
    ("immersive", "queue", "worker"),
)


def _clean(text: str) -> str:
    return ANSI_ESCAPE_RE.sub("", text).rstrip()


def _render_help(command: tuple[str, ...], runner: CliRunner) -> str:
    args = [*command, "--help"]
    result = runner.invoke(app, args, color=False)
    if result.exit_code != 0:
        joined = " ".join(args) if args else "--help"
        raise RuntimeError(f"Failed to render help for '{joined}':\n{result.output}")
    return _clean(result.output)


def _build_markdown() -> str:
    runner = CliRunner()
    lines: list[str] = []
    lines.append("# CLI Reference (Autogenerated)")
    lines.append("")
    lines.append(
        "This file is generated from live CLI help output via "
        "`scripts/generate_cli_reference.py`."
    )
    lines.append("Do not edit manually.")
    lines.append("")
    for command in HELP_COMMANDS:
        cmd_label = "verbx" if len(command) == 0 else "verbx " + " ".join(command)
        lines.append(f"## `{cmd_label} --help`")
        lines.append("")
        lines.append("```text")
        lines.append(_render_help(command, runner))
        lines.append("```")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate or validate CLI reference docs.")
    parser.add_argument(
        "--out",
        type=Path,
        default=DEFAULT_OUT,
        help="Output Markdown path (default: docs/CLI_REFERENCE.md).",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check mode: fail if the target file differs from generated content.",
    )
    args = parser.parse_args()

    generated = _build_markdown()
    target = args.out.resolve()

    if args.check:
        if not target.exists():
            print(f"Missing generated CLI reference: {target}", file=sys.stderr)
            return 2
        existing = target.read_text(encoding="utf-8")
        if existing != generated:
            print(
                "CLI reference out of date. Regenerate with:\n"
                f"  python {Path(__file__).as_posix()} --out {target.as_posix()}",
                file=sys.stderr,
            )
            return 3
        print(f"CLI reference is up to date: {target}")
        return 0

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(generated, encoding="utf-8")
    print(f"Wrote {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
